export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const RECEIVE_CATEGORIES = "RECEIVE_CATEGORIES";
export const RECEIVE_FEED = "RECEIVE_FEED";
export const RECEIVE_USER = "RECEIVE_USER";
export const TEST_ACTION = "TEST_ACTION";
